Repository hheyhhay/breathe-easy-stretch, pull requests merged in 2021-09, with the labels that each got.

#9 Feature/start form
  cypress.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.tsx
  src/Form/Form.tsx
  src/index.tsx
  src/reportWebVitals.ts
  src/setupTests.ts
  src/util/data.ts
  tsconfig.json
Labels: enhancement

#12 Feature/initial testing
  cypress/fixtures/city_test_data.json
  cypress/fixtures/selected_city_test_data.json
  cypress/integration/home_spec.js
Labels: documentation

#15 Feature/other cities component
  src/Components/App/App.css
  src/Components/App/App.tsx
  src/Components/Form/Form.tsx
  src/Components/OtherCities/OtherCities.css
  src/Components/OtherCities/OtherCities.tsx
  src/Components/OtherCity/OtherCity.css
  src/Components/OtherCity/OtherCity.tsx
  src/Components/SelectedCity/SelectedCity.css
  src/Components/SelectedCity/SelectedCity.tsx
  src/util/dataCleaning.ts
  src/util/distanceFormula.ts
Labels: enhancement

#27 Feature/responsive css
  src/Components/App/App.css
  src/Components/App/App.tsx
  src/Components/Form/Form.css
  src/Components/Form/Form.tsx
  src/Components/OtherCities/OtherCities.css
  src/Components/OtherCities/OtherCities.tsx
  src/Components/OtherCity/OtherCity.css
  src/Components/OtherCity/OtherCity.tsx
  src/Components/SelectedCity/SelectedCity.css
  src/Components/SelectedCity/SelectedCity.tsx
Labels: enhancement, help wanted

#29 Refactor/router
  src/Components/App/App.tsx
  src/Components/Error/Error.tsx
  src/Components/Form/Form.tsx
  src/Components/Loading/Loading.tsx
  src/Components/SelectedCity/SelectedCity.tsx
Labels: enhancement
